year: 2025
date: Friday, March 21nd 2025
url: https://events.eventzilla.net/e/bsides-rochester-2024--trainings-2138608764
location: Rochester Institute of Technology 1 Lomb Memorial Drive, Rochester, NY, 14623, United States
tbd: true